# Generated by Django 5.1.4 on 2025-01-06 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_problem_memory_limit_problem_time_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(max_length=255)),
                ('source_code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('result', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('memory_used', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
