# Generated by Django 5.1.4 on 2025-01-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='time_limit',
            field=models.FloatField(),
        ),
    ]
