# Generated by Django 5.1.4 on 2025-01-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_submission_outputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='outputs',
            field=models.TextField(default=''),
        ),
    ]
