# Generated by Django 5.1.4 on 2025-01-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_submission_outputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='hidden_testcases',
            field=models.FileField(blank=True, null=True, upload_to='hidden_testcases/'),
        ),
    ]
