# Generated by Django 5.1.4 on 2025-01-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_problem_hidden_testcases'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solved_count',
            field=models.IntegerField(default=0),
        ),
    ]
