# Generated by Django 5.1.4 on 2025-01-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_ratingchange_delete_solvedproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='problem_images/'),
        ),
    ]
