# Generated by Django 5.1.4 on 2025-01-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_problem_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='rating',
            field=models.IntegerField(default=100),
        ),
    ]
