# Generated by Django 5.1.4 on 2025-01-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_problem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the problem', null=True, upload_to='problem_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
